build: false

environment:
    PYTHON_HOME: "C:\\Python27"

#    CONAN_TOTAL_PAGES: 6

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 1
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_BUILD_TYPES: Release
          # CONAN_CURRENT_PAGE: 2
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_BUILD_TYPES: Release
          # CONAN_CURRENT_PAGE: 3
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_BUILD_TYPES: Release
          # CONAN_CURRENT_PAGE: 4
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_BUILD_TYPES: Release
          # CONAN_CURRENT_PAGE: 5
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_BUILD_TYPES: Release
          # CONAN_CURRENT_PAGE: 6

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
