steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
- script: |
    pip install --upgrade pip
    pip install conan_package_tools bincrafters_package_tools
    conan user
- script: python build.py
